# Generated by Django 4.2.2 on 2026-02-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_avatar_user_country_user_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["email"],
                "permissions": [("can_block_user", "can block user")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
