# Generated by Django 4.2.2 on 2026-02-20 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mailing", "0003_dispatch_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipientmail",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца подписчика",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
