# Generated by Django 4.2.2 on 2026-02-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_recipientmail_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dispatch",
            options={
                "ordering": ["start_time", "status"],
                "permissions": [("can_stop_dispatch", "can stop dispatch")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AddField(
            model_name="dispatch",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Признак активности"),
        ),
    ]
